sudo: required
dist: trusty
language: python
env:
  - JUJU_CHANNEL=stable
  - JUJU_CHANNEL=candidate
  - JUJU_CHANNEL=beta
matrix:
  allow_failures:
    - env: JUJU_CHANNEL=candidate
    - env: JUJU_CHANNEL=beta
before_install:
  # Add repositories
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
install:
  # Install packages
  - sudo apt-get -y install lxd snapd
  - sudo snap install juju --classic --channel=$JUJU_CHANNEL
  - pip install tox
before_script:
  # Setup LXD
  - sudo service lxd restart
  - sudo lxd init --auto
  - sudo usermod -a -G lxd travis
  # Changing user as a workaround for https://github.com/travis-ci/travis-ci/issues/1839
  # See http://fnordahl.com/2017/04/08/continuous-deployment-testing-of-github-hosted-code/
  - sudo su travis -c 'lxc network create lxdbr0'
  - sudo su travis -c 'lxc network attach-profile lxdbr0 default eth0'
  # Bootstrap Juju. Need to export path to snap because of workaround above
  - sudo su travis -c 'export PATH=$PATH:/snap/bin &&
                       juju bootstrap localhost'
script:
  - sudo su travis -c 'export PATH=$PATH:/snap/bin &&
                       make test'
notifications:
  email: false